### ISSUE TITLE
Show name entry if the player got a high score and they aren't using a profile

### ISSUE THREAD

**Issue by RhythmLunatic** [RhythmLunatic/raveitout#59]

**Comment by sillybear** [comment]
`for pn in ivalues(GAMESTATE:GetHumanPlayers()) do
	t[#t+1] = Def.Actor {
		Condition=not PROFILEMAN:IsPersistentProfile(pn);
		OnCommand=function(self)
			local st;
			local pss;
			local hasRecord = false;
		
			for i=1, STATSMAN:GetStagesPlayed() do
				st = STATSMAN:GetPlayedStageStats( i );
				pss = st:GetPlayerStageStats( pn );
				
				if pss:GetMachineHighScoreIndex() == 0 then
					hasRecord = true;
					break
				end
			end

			if not hasRecord then
				SCREENMAN:GetTopScreen():Finish(pn);
			end
		end;
	};
};`

**Comment by sillybear** [comment]
```
for pn in ivalues(GAMESTATE:GetHumanPlayers()) do
	t[#t+1] = Def.Actor {
		Condition=not PROFILEMAN:IsPersistentProfile(pn);
		OnCommand=function(self)
			local st;
			local pss;
			local hasRecord = false;
		
			for i=1, STATSMAN:GetStagesPlayed() do
				st = STATSMAN:GetPlayedStageStats( i );
				pss = st:GetPlayerStageStats( pn );
				
				if pss:GetMachineHighScoreIndex() == 0 then
					hasRecord = true;
					break
				end
			end

			if not hasRecord then
				SCREENMAN:GetTopScreen():Finish(pn);
			end
		end;
	};
};
```
